server-name smartdns
bind :6053
bind-tcp :6053
cache-size 512
prefetch-domain yes
serve-expired yes
response-mode fastest-response
log-level info
server 223.5.5.5
server 119.29.29.29
server 1.1.1.1
server 8.8.8.8
plugin smartdns_ui.so
smartdns-ui.conf-file /etc/smartdns/smartdns.conf
smartdns-ui.www-root /usr/share/smartdns/wwwroot
smartdns-ui.ip http://0.0.0.0:6080
smartdns-ui.token-expire 600
smartdns-ui.max-query-log-age 86400
smartdns-ui.enable-terminal yes
smartdns-ui.enable-cors yes
smartdns-ui.user admin
smartdns-ui.password password
